### ISSUE TITLE
consider streamlining preambles

### ISSUE THREAD

**Issue by beanumber** [bmacGTPM/rticles#8]
I'd recommend either condensing the three preambles into one, or dropping them altogether.

- The `Common` preamble is all commented out, so it's not actually doing anything. 
- The only difference between the Arxiv and the DeGruyter template is the use of `dgjournal`. I'd recommend just moving this stuff into `template.tex`. 
- Why does this package need to support the arXiv version? This seems like it is beyond the scope of this pull request. An arXiv template seems like it should be it's own `rticles` template, not a piggy-back on the `degruyter` template

So I think if you move the preamble material into `template.tex`, forget about the arXiv, and get rid of all of the preambles, you'll have a cleaner contribution.

**Comment by bmacGTPM** [comment]
Ok I cleaned it up.  When I tried moving the stuff from the preambles to the `template.tex`, the changes weren't being recognized.  I finally realized that I should have had `output: rticles::degruyter_article` instead of  `output: pdf_document` in `skeleton.rmd`.  So I changed that, and it's seems to be working. 

The nice thing about it is that now we don't have to keep the front matter commented out.  It simply ignores title, author, etc., because I edited `template.tex` so that there is no `\title`, `\author`, etc. anywhere.

There's no need to have the arXiv stuff that I had so I removed it.  You can switch to knit as pdf_document and the front matter will show up, which is good enough for now. 

It might be worth creating an arxiv_article template though.  The pdf_document output might be good enough for arXiv, or it might need some tweaks.  I'll look into it after this degruyter template is done.

**Comment by beanumber** [comment]
Is that for blinding? How about if we add an option to blind?

**Comment by bmacGTPM** [comment]
Would be useful for other output formats. I think it may not do anything with `degruyter_article` because the degruyter tex package will ignore title/author/etc.  Even for the final submission those aren't allowed in the document. They are entered on the website instead.
